<?php
$date = '03_03_2017';
$current_crawl = "btc_{$date}";
$urls_file = "btc.csv";
$country_column = 0;
$url_column = 2;

$ec2_locations['Gtech_US']['count'] = 900;
$ec2_locations['Gtech_Ireland']['count'] = 300;
$ec2_locations['Gtech_Singapore']['count'] = 60;
$ec2_locations['Gtech_Japan']['count'] = 80;
$ec2_locations['Gtech_Australia']['count'] = 150;
$ec2_locations['Gtech_Brazil']['count'] = 80;
?>
